version: 2
jobs:
  build:
    docker:
      - image: technekes/circleci

    working_directory: /tmp/app

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build the image
          command: |
                  docker build -t $CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH .

                  CONTAINER_VERSION=$(docker inspect -f {{.Config.Labels.version}} $CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH)
                  
                  echo $CONTAINER_VERSION

                  #Check if version already has a release
                  curl https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/releases/tags/v0.0.1 #| grep "Not Found"

      - run:
          name: Run tests
          command: |
                  docker run -it example:$CIRCLE_BRANCH | tee output

      - run: 
          name: Verify tests output
          command: |
                  grep "day" output

      # Deploy development
      - deploy:
          name: Push branch tagged image to development repo
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ];
              then echo "Deploy dev";
            fi

      # Deploy production, tag on master
      - deploy:
          name: Push tagged release to production repo
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ -z "${CIRCLE_TAG}" ];
              then echo "Tag on master";
            fi

      # Deploy development beta, no tag on master
      - deploy:
          name: Push beta release to development repo
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then echo "No tag on master";
            fi

